homepage:
    path: /
    controller: App\Controller\HomepageController::index
sing_up:
    path: /sing-up
    controller: App\Controller\RegistrationController::singUp
sing_in:
    path: /sing-in
    controller: App\Controller\LoginController::singIn
    methods: GET|POST
log_out:
    path: /log-out
    controller: App\Controller\LoginController::logOut
all_posts_list:
    path: /posts
    controller: App\Controller\PostsController::allPosts
user_posts_list:
    path: /my-posts
    controller: App\Controller\PostsController::userPosts
user_account:
    path: /account
    controller: App\Controller\UserController::userAccount

