App\Entity\User:
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 3
                minMessage: 'Your username must be at least {{ limit }} characters long'
        email:
            - NotBlank: ~
            - Email:
                message: The email "{{ value }}" is not a valid email.
        password:
            - NotBlank:
                message: 'Passwords must be the same'
            - Length:
                min: 3
                minMessage: 'Your password must be at least {{ limit }} characters long'
